# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=dev.br0b

# Dependencies
fabric_api_version=0.154.2+26.1.2
pty4j_version=0.13.10
jediterm_core_version=3.73
kotlin_stdlib_version=2.4.0
jna_version=5.17.0
jetbrains_annotations_version=24.0.1
